import { AutoFix } from "./types";
import { TextEdit, TextDocument, Diagnostic } from "vscode-languageserver";
import URI from "vscode-uri";
export declare function computeKey(diagnostic: Diagnostic): string;
export declare function sortFixes(fixes: AutoFix[]): AutoFix[];
export declare function getLastEdit(array: AutoFix[]): AutoFix | undefined;
export declare function overlaps(lastFix: AutoFix | undefined, nextFix: AutoFix): boolean;
export declare function createTextEdit(autoFix: AutoFix): TextEdit[];
export declare function concatenateEdits(fixes: AutoFix[]): TextEdit[];
export declare function getFileSystemPath(uri: URI): string;
export declare function getFilePath(documentOrUri: string | TextDocument): string;
export declare function getAllNonOverlappingFixes(fixes: AutoFix[]): [AutoFix[], boolean];
